name: pdf_viewer_example
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  # display PDF
  flutter_pdfview: ^1.0.0+10
  dependencies:
  native_pdf_view: ^4.0.1
  pdf: ^2.1.0
  image_picker: ^0.6.7+21
  flushbar: ^1.10.4
  lottie:
  printing:

  # path
  file_picker: ^2.1.6
  path: ^1.7.0
  path_provider: ^1.6.27
  images_to_pdf: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/